### ISSUE TITLE
format for IBM_TRANSLATOR_API_CREDENTIALS.sh

### ISSUE THREAD

**Issue by johnfelipe** [warren-bank/node-translate-webextension-strings#1]

**Comment by warren-bank** [comment]
it should look something like this..

```bash
#!/usr/bin/env bash

export IBM_TRANSLATOR_API_KEY='xxxxx'
export IBM_TRANSLATOR_API_URL='https://api.us-south.language-translator.watson.cloud.ibm.com/instances/xxxxx'
```

..using values that IBM gives you for your account

**Comment by warren-bank** [comment]
and on Windows, _IBM_TRANSLATOR_API_CREDENTIALS.bat_ should look something like..

```bash
@echo off

set IBM_TRANSLATOR_API_KEY=xxxxx
set IBM_TRANSLATOR_API_URL=https://api.us-south.language-translator.watson.cloud.ibm.com/instances/xxxxx
```

**Comment by johnfelipe** [comment]
i change this

	source "${HOME}/node-translate-webextension-strings/IBM_TRANSLATOR_API_CREDENTIALS.sh"

	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

	function translate-webextension-strings {
	  node "/root/node-translate-webextension-strings/bin/translate-webextension-strings.js" "$@"
	}

and show me this error:

	/root/node-translate-webextension-strings/node_modules/@warren-bank/ibm-watson-language-translator/lib/optimize-duplicates/duplicates_store.js:7
	  normalized_input_strings_array = null
									 ^

	SyntaxError: Unexpected token =
		at Module._compile (internal/modules/cjs/loader.js:723:23)
		at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
		at Module.load (internal/modules/cjs/loader.js:653:32)
		at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
		at Function.Module._load (internal/modules/cjs/loader.js:585:3)
		at Module.require (internal/modules/cjs/loader.js:692:17)
		at require (internal/modules/cjs/helpers.js:25:18)
		at Object.<anonymous> (/root/node-translate-webextension-strings/node_modules/@warren-bank/ibm-watson-language-translator/lib/optimize-duplicates/index.js:1:25)
		at Module._compile (internal/modules/cjs/loader.js:778:30)
		at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by johnfelipe** [comment]
root@felipe:~/node-translate-webextension-strings/tests/03-xrengine# node -v
    v10.19.0

**Comment by warren-bank** [comment]
is your project public? ..if so, i'll run it here and see if I can reproduce the error.

**Comment by warren-bank** [comment]
ps.. i'm using node v16.14.0 ..and haven't used/tested v10.x in a long time. It's possible that I added some code that it doesn't like. Offhand, not sure.

**Comment by johnfelipe** [comment]
[admin.zip](https://github.com/warren-bank/node-translate-webextension-strings/files/8839230/admin.zip)

i update to v18.3.0
ubuntu 20

show me 

ERROR: Failed to extract strings from input file

**Comment by johnfelipe** [comment]
> is your project public? ..if so, i'll run it here and see if I can reproduce the error.

not is locally

**Comment by warren-bank** [comment]
[here](https://developer.chrome.com/docs/extensions/mv3/i18n-messages/) is the spec for how to do i18n localization in a webextension.

[here](https://github.com/warren-bank/node-translate-webextension-strings/blob/master/tests/02-skip-duplicates/1-input/_locales/en/messages.json) is a working example that's a part of this repo.

the file you just handed me looks absolutely nothing like this spec.. the format (ie: JSON schema) is entirely different.

**Comment by johnfelipe** [comment]
then is not possible with my format:

	{
	  "components": {
		"locationModal": {
		  "lbl-name": "Name",
		  "lbl-maxuser": "Max Users",
		  "lbl-scene": "Scene",
		  "lbl-sceneId": "Scene ID",
		  "lbl-type": "Type",
		  "lbl-ve": "Video Enabled",
		  "lbl-gme": "Global Media Enabled",
		  "lbl-lobby": "Make Lobby",
		  "lbl-featured": "Featured",
		  "lbl-update": "Update",
		  "lbl-create": "Create",
		  "lbl-cancel": "Cancel",
		  "lbl-delete": "Delete",
		  "lbl-edit": "Edit",
		  "tooltipCanNotBeDeleted": "Lobby can't be deleted",
		  "lbl-ae": "Audio Enabled",
		  "lbl-se": "Screen Sharing Enabled",
		  "lbl-fe": "Face Streaming Enabled",
		  "createNewLocation": "Create New Location",
		  "selectScene": "Select scene",
		  "private": "Private",
		  "type": "Type",
		  "selectType": "Select type",
		  "submit": "Submit",
		  "fillRequiredFields": "Please fill all required field",
		  "sceneCantEmpty": "Scene can't be empty",
		  "maxUserCantEmpty": "Max users can't be empty",
		  "nameCantEmpty": "Name can't be empty",
		  "typeCantEmpty": "Type can't be empty",
		  "nameRequired": "Name is required!",
		  "maxUsersRequired": "Max users is required!",
		  "sceneRequired": "Scene is required!",
		  "privateRoleRequired": "Private role is required!",
		  "updateLocationInfo": "Update location Information",
		  "enterName": "Enter name",
		  "enterMaxUsers": "Enter max users",
		  "slugyName": "Slugy Name",
		  "none": "None",
		  "locationSettings": "Location Settings",
		  "locationType": "Location Type",
		  "videoEnabled": "Video Enabled",
		  "audioEnabled": "Audio Enabled",
		  "faceStreamingEnabled": "Face Streaming Enabled",
		  "screenSharingEnabled": "Screen Sharing Enabled",
		  "mediaChatEnabled": "Media Chat Enabled",
		  "isRequired": "is required!"
		},
		"index": {
		  "col-id": "ID",
		  "col-name": "Name",
		  "col-scene": "Scene",
		  "col-maxuser": "Max Users",
		  "col-type": "Type",
		  "col-tags": "Tags",
		  "col-mc": "Enable public media chat",
		  "col-ve": "Video Enabled",
		  "col-instanceId": "Instance ID",
		  "col-userRole": "User Role",
		  "col-partyId": "Party ID",
		  "col-ip": "IP address",
		  "col-gameserverID": "Gameserver ID",
		  "col-publicAddress": "Public address",
		  "col-currentUsers": "Current # of Users",
		  "col-locationId": "Location ID",
		  "lbl-newLocation": "Create New Location",
		  "lbl-locations": "Locations",
		  "lbl-users": "Users",
		  "lbl-instances": "Instances",
		  "lobby": "Lobby",
		  "featured": "Featured",
		  "view": "View",
		  "delete": "Delete",
		  "yes": "Yes",
		  "no": "No",
		  "none": "None"
		},
		"bot": {
		  "uniqueCommand": "Command should be unique",
		  "commandRequired": "Fill in command is required!",
		  "nameCantEmpty": "Name can't be empty",
		  "descriptionCantEmpty": "Description can't be empty",
		  "locationCantEmpty": "Location can't be empty",
		  "fillRequiredField": "Please fill all required field",
		  "createNewBot": "Create new bot",
		  "addMoreBots": "Add more bots in the system.",
		  "location": "Location",
		  "instance": "Instance",
		  "addMoreCommand": "Add more command",
		  "command": "Command",
		  "enterCommand": "Enter command",
		  "description": "Description",
		  "addCommand": "Add command",
		  "enterDescription": "Enter description",
		  "spawnBot": "Spawn Bot",
		  "lastRunStatus": "Last run status",
		  "autoRefreshing": "auto refreshing in 10s",
		  "xrEngineBots": "XREngine bots",
		  "updateBot": "UPDATE BOT",
		  "selectLocation": "Select location",
		  "selectInstance": "Select instance",
		  "cancel": "Cancel",
		  "save": "Save",
		  "name": "Name"
		},
		"common": {
		  "doYouWantTo": "Do you want to",
		  "cancel": "Cancel",
		  "confirm": "Confirm",
		  "new": "new",
		  "select": "Select"
		},
		"analytics": {
		  "analytics": "Analytics",
		  "activeParties": "Active Parties",
		  "activeLocations": "Active Locations",
		  "activeInstances": "Active Instances",
		  "activeScenes": "Active Scenes",
		  "instanceUsers": "Instance Users",
		  "channelUsers": "Channel Users",
		  "dailyUsers": "Daily Users",
		  "dailyNewUsers": "Daily New Users",
		  "usersToday": "Users Today",
		  "newUsersToday": "New Users Today",
		  "port": "Port",
		  "processInterval": "Process Interval"
		},
		"group": {
		  "createNewGroup": "Create New Group",
		  "name": "Name",
		  "enterGroupName": "Enter group name",
		  "description": "Description",
		  "enterGroupDescription": "Enter description",
		  "submit": "Submit",
		  "cancel": "Cancel",
		  "view": "View",
		  "edit": "Edit",
		  "delete": "Delete",
		  "nameCantEmpty": "Name can't be empty",
		  "descriptionCantEmpty": "Description can't be empty",
		  "scopeCantEmpty": "Scope can't be empty",
		  "createGroup": "Create Group",
		  "editGroup": "Edit group",
		  "grantScope": "Grant Scope",
		  "usersInformation": "Users Information",
		  "groupScopes": "Group scopes",
		  "groupInformation": "Group Information"
		},
		"invite": {
		  "sendInvite": "Send Invite",
		  "receivedInvite": "Received Invite",
		  "fillAllRequiredFields": "Please fill all required fields!",
		  "enterValidPasscode": "Enter valid Passcode or None",
		  "invalidInviteCode": "Invalid Invite Code",
		  "targetType": "Target type",
		  "identityProviderType": "Identity provider type",
		  "enterPhoneOrEmail": "Please enter US phone number or E-mail",
		  "cancel": "Cancel",
		  "sendInvitation": "Send Invitation",
		  "name": "Name",
		  "passcode": "Passcode",
		  "type": "Type",
		  "action": "Action"
		},
		"party": {
		  "locationRequired": "Location is required",
		  "instanceRequired": "Instance is required",
		  "locationCantEmpty": "Location can't be empty",
		  "instanceCantEmpty": "Instance can't be empty",
		  "instance": "Instance",
		  "location": "Location",
		  "selectInstance": "Select instance",
		  "selectLocation": "Select location",
		  "createOne": "Create One",
		  "dontSeeLocation": "Don't see Location?",
		  "createNewParty": "Create New Party",
		  "partyWithInstanceOf": "party with instance of",
		  "updateParty": "Update party",
		  "ipAddress": "Ip Address",
		  "user": "User",
		  "active": "Active",
		  "submit": "Submit",
		  "cancel": "Cancel",
		  "edit": "Edit"
		},
		"project": {
		  "name": "Name",
		  "update": "Update",
		  "invalidateCache": "Invalidate Cache",
		  "viewProjectFiles": "View Project Files",
		  "remove": "Remove",
		  "addProject": "Add Project",
		  "rebuild": "Rebuild",
		  "project": "Project",
		  "storageProvidersCacheOf": "storage provider's cache of",
		  "selectProject": "Select Project",
		  "insertPublicUrl": "Please insert github public url",
		  "uploadProject": "Upload Project",
		  "customPublicUrl": "Custom Public Url",
		  "selectFromList": "Select From List",
		  "processing": "Processing"
		},
		"scene": {
		  "sceneInfo": "Scene Information",
		  "entityInfo": "Entity Information",
		  "type": "Type",
		  "sid": "SID",
		  "entities": "Entities",
		  "version": "Version",
		  "description": "Description"
		},
		"setting": {
		  "authentication": "AUTHENTICATION",
		  "service": "Service",
		  "secret": "Secret",
		  "entity": "Entity",
		  "authStrategies": "Authentication Strategies",
		  "local": "Local",
		  "userName": "User Name",
		  "password": "Password",
		  "oauth": "OAUTH",
		  "defaults": "Defaults",
		  "host": "Host",
		  "protocol": "Protocol",
		  "discord": "Discord",
		  "facebook": "Facebook",
		  "google": "Google",
		  "github": "Github",
		  "linkedIn": "LinkedIn",
		  "twitter": "Twitter",
		  "key": "Key",
		  "callback": "Callback",
		  "appId": "App ID",
		  "appTitle": "App Title",
		  "appSubtitle": "App Subtitle",
		  "appDescription": "App Description",
		  "appBackground": "App Background",
		  "appSocialLinks": "Social Links",
		  "icon": "Icon",
		  "link": "Link",
		  "cancel": "Cancel",
		  "save": "Save",
		  "resetTheme": "Reset to Default",
		  "aws": "AWS",
		  "keys": "Keys",
		  "accessKeyId": "Access Key ID",
		  "secretAccessKey": "Secret Access Key",
		  "route53": "Route53",
		  "hostedZoneId": "Hosted Zone ID",
		  "s3": "S3",
		  "baseUrl": "BaseUrl",
		  "staticResourceBucket": "Static Resource Bucket",
		  "region": "Region",
		  "avatarDir": "AvatarDir",
		  "s3DevMode": "S3DevMode",
		  "domain": "Domain",
		  "distributionId": "Distribution ID",
		  "cloudFront": "Cloud Front",
		  "sms": "SMS",
		  "applicationId": "Application ID",
		  "senderId": "Sender ID",
		  "apiKey": "ApiKey",
		  "url": "URL",
		  "chargebee": "CHARGEBEE",
		  "client": "CLIENT",
		  "clientId": "OAuth2 client_id",
		  "clientSecret": "OAuth2 client_secret",
		  "coil": "Coil",
		  "coilPaymentPointer": "Payment Pointer",
		  "title": "Title",
		  "description": "Description",
		  "logo": "Logo",
		  "icon192px": "Icon 192px",
		  "icon512px": "Icon 512px",
		  "favIcon16px": "FavIcon 16px",
		  "favIcon32px": "FavIcon 32px",
		  "releaseName": "Release Name",
		  "email": "EMAIL",
		  "smtp": "SMTP",
		  "port": "Port",
		  "secure": "Secure",
		  "auth": "Auth",
		  "from": "From",
		  "subject": "Subject",
		  "login": "login",
		  "friend": "friend",
		  "group": "group",
		  "party": "Party",
		  "smsNameCharLimit": "SMS Name Character Limit",
		  "gameServer": "GAME SERVER",
		  "clientHost": "Client Host",
		  "rtcStartPort": "rtc_start_port",
		  "rtcEndPort": "rtc_end_port",
		  "rtcPortBlockSize": "rtc_port_block_size",
		  "identifierDigits": "Identifier Digits",
		  "mode": "Mode",
		  "locationName": "Location Name",
		  "settings": "Settings",
		  "redis": "REDIS",
		  "enabled": "Enabled",
		  "address": "Address",
		  "server": "SERVER",
		  "hostName": "Host Name",
		  "rootDirectory": "Root Directory",
		  "publicDirectory": "Public Directory",
		  "nodeModulesDirectory": "Node Modules Directory",
		  "localStorageProvider": "Local StorageProvider",
		  "performDryRun": "Perform Dry Run",
		  "storageProvider": "Storage Provider",
		  "googleAnalyticsTrackingId": "Google Analytics Tracking ID",
		  "certPath": "CertPath",
		  "keyPath": "KeyPath",
		  "githubPrivateKey": "Github Private Key",
		  "project": "PROJECT",
		  "selectProject": "Select Project",
		  "patchGameserver": "Patch Gameserver"
		},
		"avatar": {
		  "fillRequiredFields": "Please fill all required field",
		  "avatarUrlCantEmpty": "Avatar url can't be empty",
		  "avatarCantEmpty": "Avatar can't be empty",
		  "descriptionCantEmpty": "Description can't be empty",
		  "nameCantEmpty": "Name can't be empty"
		},
		"dialog": {
		  "notAccess": "No access",
		  "askAccessResourceMessage": "To access this resource, please enter your username here to ask for access or login to continue.",
		  "login": "Login",
		  "submit": "Submit"
		},
		"user": {
		  "nameCantEmpty": "Name can't be empty",
		  "avatarCantEmpty": "Avatar can't be empty",
		  "userRoleCantEmpty": "User role can't be empty",
		  "scopeTypeCantEmpty": "Scope type can't be empty",
		  "fillRequiredField": "Please fill all required field",
		  "createNewUser": "Create New User",
		  "dontSeeUserRole": "Don't see user role?",
		  "createOne": "Create One",
		  "submit": "Submit",
		  "edit": "Edit",
		  "cancel": "Cancel",
		  "isRequired": "is required!",
		  "hideGuests": "Hide guests",
		  "updatePersonalInfo": "Update personal Information",
		  "name": "Name",
		  "avatar": "Avatar",
		  "role": "Role",
		  "selectAvatar": "Select avatar",
		  "userRole": "User Role",
		  "grantScope": "Grant Scope",
		  "personalInfo": "Personal Information",
		  "location": "Location",
		  "inviteCode": "Invite Code",
		  "instance": "Instance",
		  "userScope": "User scope",
		  "enterName": "Enter name"
		}
	  }
	}

**Comment by johnfelipe** [comment]
im using https://www.ibm.com/demos/live/watson-language-translator/self-service/home

![SNAG-1187](https://user-images.githubusercontent.com/428820/172033295-5f5e5984-10af-47dd-8622-42ef1347756b.png)

and translate it correctly

**Comment by warren-bank** [comment]
it should be pretty simple to fork this repo and customize it for your own needs..

but this tool is designed to extract strings from a particular JSON schema..
and write translated output to files having the same JSON schema..
and organize the files produced into a very specific directory hierarchy that is used by webextensions.

as the name of the project indicates.. it's designed to suit a very particular purpose.
the upstream library [node-ibm-watson-language-translator](https://github.com/warren-bank/node-ibm-watson-language-translator) is performing all of the actual translation,
which you can also use.. to build whatever you like.
